name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          # Install all dependencies including dev dependencies
          npm install --legacy-peer-deps
          # Ensure ajv and webpack dependencies are installed
          npm install --legacy-peer-deps ajv@8 @expo/webpack-config@19 html-webpack-plugin@5 webpack@5 webpack-cli@6 webpack-dev-server@5

      - name: Clear cache
        run: |
          rm -rf .expo
          rm -rf node_modules/.cache

      - name: Build for web
        run: |
          # Set the base path for GitHub Pages
          export EXPO_PUBLIC_BASE_PATH="/${{ github.event.repository.name }}"
          npx expo export --platform web --output-dir dist --base-path "/${{ github.event.repository.name }}"
          echo "Build completed, checking output..."
          ls -la dist/
        env:
          NODE_ENV: production
          CI: true
          PUBLIC_URL: /${{ github.event.repository.name }}

      - name: Add 404 fallback and base path fix
        run: |
          # Copy index.html to 404.html for client-side routing
          cp dist/index.html dist/404.html
          
          # Add .nojekyll to prevent Jekyll processing
          touch dist/.nojekyll
          
          # Fix asset paths in HTML files for GitHub Pages
          sed -i 's|href="/|href="/${{ github.event.repository.name }}/|g' dist/index.html
          sed -i 's|src="/|src="/${{ github.event.repository.name }}/|g' dist/index.html
          sed -i 's|href="/|href="/${{ github.event.repository.name }}/|g' dist/404.html
          sed -i 's|src="/|src="/${{ github.event.repository.name }}/|g' dist/404.html
          
          echo "Files in dist after setup:"
          ls -la dist/
          echo "Content of index.html (first 20 lines):"
          head -20 dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
